name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build and Restore"
    uses: ./.github/workflows/dotnet.yml
  deploy:
    name: "Create docker image and deploy to Heroku"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          docker_heroku_process_type: web
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true

      - name: "Login to heroku registry"
        run: heroku container:login

      - name: "Build and push to heroku registry"
        run: heroku container:push web --app wheels-and-goods-api

      - name: "Releases the container"
        run: heroku container:release web --app wheels-and-goods-api
  migrate:
    name: "Apply migrations to DB"
    needs: [deploy]
    uses: ./.github/workflows/db_migrate.yml
